### ISSUE TITLE
Dataordbog

### ISSUE THREAD

**Issue by sasaje** [LouiseFuglsang/New-Yorker.dk#19]

**Comment by LouiseFuglsang** [comment]
Find den under punktet Wiki (ved siden af Projects)

**Comment by sasaje** [comment]
## Review fra: sasaje ##
Kommentarer står med **bold**

EnviromentType - **ja det er det.**

Fag - En glasvæg opdeles i bredden via stellet, og bredden mellem to stel kaldes et fag. Der kan være mange glas mellem stellene i højden, det er kun bredden et fag definerer. - **Kald det for rammen i stedet for stellet.** 

Glas - Højden på glasvæggen omtales også som antal glas i højden udover den faktiske højde i centimeter. - **Tilføj evt. "glas er det materiale, som findes i felterne, som udgøre en new yorker væg". "Glas kan også defineres i forskellige glastyper, fx. safinglas, frosted glas m.fl."** 

Mounting - Montering - **Tilføj evt. "Montering gør, at der kan vælges en væg på hjul, som derfor ikke skal monteres."**

QuotationRequest - Tilbudsforespørgsel - **Tilføj evt. "Omtales også som QR"**

Ellers super fint :)
