### ISSUE TITLE
Kravspecifikation

### ISSUE THREAD

**Issue by sasaje** [LouiseFuglsang/New-Yorker.dk#21]

**Comment by LouiseFuglsang** [comment]
Under "Need to have" synes jeg du skal slette "Har ikke login-funktion (for brugervenlighedens skyld)", da vi i så fald kan skrive mange ting som systemet ikke skal indeholde.

Under "Nice to have" synes jeg du skal slette "(kan godt lade sig gøre, men er svært at realisere inde for tidsfristen)", da det er vores konkludering og ikke et element i kravspecifisering, selve elementet står så fint uden kommentaren i parantesen :)

Ellers synes jeg det ser fint ud.
