### ISSUE TITLE
Use Case 1 brief

### ISSUE THREAD

**Issue by sasaje** [LouiseFuglsang/New-Yorker.dk#9]

**Comment by LouiseFuglsang** [comment]
Jeg synes du skal ændre "Herefter godkender brugeren indholdet af tilbuddet" til "Brugeren godkender indholdet af tilbuddet", så det holder formen.

"En bruger af appen repræsenterer tre målgrupper: ..." skal ændres til "Brugeren er en fra de tre målgrupper den repræsenterer: tømrer, forhandler...."

Ellers er det rigtig fint :)
